### ISSUE TITLE
loop() send only single message

### ISSUE THREAD

**Issue by neitri** [nomis/mcu-uuid-syslog#3]
Hello.
The loop method sends only one message from the queue. I expect that by calling the loop I will receive all the messages from the queue.
I found that the reason is in the can_transmit method. message_delay is assigned 10 ms. And sending one packet takes a little more than 1ms (32 packets are sent in 41ms)
I send broadcast packets.
I don't understand the purpose of this delay?

**Comment by nomis** [comment]
The delay is because the ESP outgoing UDP buffer has a limited number of packets it can queue. Sending too many at once just results in most of them being discarded before they can be transmitted.

There will only ever be one per loop() call because it's intended to be asynchronous and not stop other processes from having time to run too.

**Comment by neitri** [comment]
My application runs for 5 seconds. Network connection takes 4 seconds, 1 second sends data to the server. When finished, he goes to sleep. The device is powered by batteries.
I'd like to send the entire queue at once in a reasonable amount of time.
But the library lacks functions that would return the length of the queue, or send everything.

**Comment by nomis** [comment]
I will add a function to return how many messages are queued.

If you want to send everything you'll have to call loop() until the queue is empty.

It still won't be practical to send everything without delays. Even if I could query the size of the network UDP packet buffer, there's nothing to stop another part of the platform (DHCP, DNS, NTP) making a UDP query causing a message to be lost.

**Comment by nomis** [comment]
Fixed in 2.1.0: [SyslogService::current_log_messages()](https://mcu-doxygen.uuid.uk/classuuid_1_1syslog_1_1SyslogService.html#a9863961155b0354b583f705bf2d7ac39)

You can also change the rate at which messages are sent but I don't recommend doing that:
https://github.com/nomis/mcu-uuid-syslog/commit/4daaa65b0e32788eeef9051874d4109043068873#diff-1bea5a4daeee768dfdab0355d71f10b0667c32602af4661b2565ae61193d0498

It won't go any faster than 1 packet every 1ms.
